/// Character data model for better organization
class CharacterData {
  final String id;
  final String displayName;
  final String assetName;

  const CharacterData({
    required this.id,
    required this.displayName,
    required this.assetName,
  });
}

/// List of all available characters in Genshin Impact
/// IDs are normalized for consistency, asset names match actual file names
const List<CharacterData> genshinCharactersData = [
  // 5-Star Characters
  CharacterData(id: 'albedo', displayName: 'Albedo', assetName: 'albedo'),
  CharacterData(
    id: 'alhaitham',
    displayName: 'Alhaitham',
    assetName: 'alhaitham',
  ),
  CharacterData(id: 'aloy', displayName: 'Aloy', assetName: 'aloy'),
  CharacterData(
    id: 'arlecchino',
    displayName: 'Arlecchino',
    assetName: 'arlecchino',
  ),
  CharacterData(id: 'ayaka', displayName: 'Kamisato Ayaka', assetName: 'ayaka'),
  CharacterData(id: 'ayato', displayName: 'Kamisato Ayato', assetName: 'ayato'),
  CharacterData(id: 'baizhu', displayName: 'Baizhu', assetName: 'baizhu'),
  CharacterData(id: 'chasca', displayName: 'Chasca', assetName: 'chasca'),
  CharacterData(id: 'chiori', displayName: 'Chiori', assetName: 'chiori'),
  CharacterData(id: 'citlali', displayName: 'Citlali', assetName: 'citlali'),
  CharacterData(id: 'clorinde', displayName: 'Clorinde', assetName: 'clorinde'),
  CharacterData(id: 'cyno', displayName: 'Cyno', assetName: 'cyno'),
  CharacterData(id: 'dehya', displayName: 'Dehya', assetName: 'dehya'),
  CharacterData(id: 'diluc', displayName: 'Diluc', assetName: 'diluc'),
  CharacterData(id: 'emilie', displayName: 'Emilie', assetName: 'emilie'),
  CharacterData(
    id: 'escoffier',
    displayName: 'Escoffier',
    assetName: 'escoffier',
  ),
  CharacterData(id: 'eula', displayName: 'Eula', assetName: 'eula'),
  CharacterData(id: 'flins', displayName: 'Flins', assetName: 'flins'),
  CharacterData(id: 'furina', displayName: 'Furina', assetName: 'furina'),
  CharacterData(id: 'ganyu', displayName: 'Ganyu', assetName: 'ganyu'),
  CharacterData(id: 'hutao', displayName: 'Hu Tao', assetName: 'hutao'),
  CharacterData(id: 'itto', displayName: 'Arataki Itto', assetName: 'itto'),
  CharacterData(id: 'jean', displayName: 'Jean', assetName: 'jean'),
  CharacterData(
    id: 'kazuha',
    displayName: 'Kaedehara Kazuha',
    assetName: 'kazuha',
  ),
  CharacterData(id: 'keqing', displayName: 'Keqing', assetName: 'keqing'),
  CharacterData(id: 'kinich', displayName: 'Kinich', assetName: 'kinich'),
  CharacterData(id: 'klee', displayName: 'Klee', assetName: 'klee'),
  CharacterData(
    id: 'kokomi',
    displayName: 'Sangonomiya Kokomi',
    assetName: 'kokomi',
  ),
  CharacterData(id: 'lyney', displayName: 'Lyney', assetName: 'lyney'),
  CharacterData(id: 'mavuika', displayName: 'Mavuika', assetName: 'mavuika'),
  CharacterData(id: 'mona', displayName: 'Mona', assetName: 'mona'),
  CharacterData(id: 'mualani', displayName: 'Mualani', assetName: 'mualani'),
  CharacterData(id: 'nahida', displayName: 'Nahida', assetName: 'nahida'),
  CharacterData(id: 'navia', displayName: 'Navia', assetName: 'navia'),
  CharacterData(
    id: 'neuvillette',
    displayName: 'Neuvillette',
    assetName: 'neuvillette',
  ),
  CharacterData(id: 'nilou', displayName: 'Nilou', assetName: 'nilou'),
  CharacterData(id: 'qiqi', displayName: 'Qiqi', assetName: 'qiqi'),
  CharacterData(
    id: 'raiden',
    displayName: 'Raiden Shogun',
    assetName: 'raiden',
  ),
  CharacterData(id: 'shenhe', displayName: 'Shenhe', assetName: 'shenhe'),
  CharacterData(
    id: 'sigewinne',
    displayName: 'Sigewinne',
    assetName: 'sigewinne',
  ),
  CharacterData(
    id: 'tartaglia',
    displayName: 'Tartaglia',
    assetName: 'tartaglia',
  ),
  CharacterData(id: 'tighnari', displayName: 'Tighnari', assetName: 'tighnari'),
  CharacterData(id: 'venti', displayName: 'Venti', assetName: 'venti'),
  CharacterData(id: 'wanderer', displayName: 'Wanderer', assetName: 'wanderer'),
  CharacterData(
    id: 'wriothesley',
    displayName: 'Wriothesley',
    assetName: 'wriothesley',
  ),
  CharacterData(id: 'xiao', displayName: 'Xiao', assetName: 'xiao'),
  CharacterData(id: 'xianyun', displayName: 'Xianyun', assetName: 'xianyun'),
  CharacterData(id: 'xilonen', displayName: 'Xilonen', assetName: 'xilonen'),
  CharacterData(id: 'yae', displayName: 'Yae Miko', assetName: 'yae'),
  CharacterData(id: 'yelan', displayName: 'Yelan', assetName: 'yelan'),
  CharacterData(id: 'yoimiya', displayName: 'Yoimiya', assetName: 'yoimiya'),
  CharacterData(id: 'zhongli', displayName: 'Zhongli', assetName: 'zhongli'),

  // 4-Star Characters
  CharacterData(id: 'aino', displayName: 'Aino', assetName: 'aino'),
  CharacterData(id: 'amber', displayName: 'Amber', assetName: 'amber'),
  CharacterData(id: 'barbara', displayName: 'Barbara', assetName: 'barbara'),
  CharacterData(id: 'beidou', displayName: 'Beidou', assetName: 'beidou'),
  CharacterData(id: 'bennett', displayName: 'Bennett', assetName: 'bennett'),
  CharacterData(id: 'candace', displayName: 'Candace', assetName: 'candace'),
  CharacterData(
    id: 'charlotte',
    displayName: 'Charlotte',
    assetName: 'charlotte',
  ),
  CharacterData(
    id: 'chevreuse',
    displayName: 'Chevreuse',
    assetName: 'chevreuse',
  ),
  CharacterData(id: 'chongyun', displayName: 'Chongyun', assetName: 'chongyun'),
  CharacterData(id: 'collei', displayName: 'Collei', assetName: 'collei'),
  CharacterData(id: 'dahlia', displayName: 'Dahlia', assetName: 'dahlia'),
  CharacterData(id: 'diona', displayName: 'Diona', assetName: 'diona'),
  CharacterData(id: 'dori', displayName: 'Dori', assetName: 'dori'),
  CharacterData(id: 'faruzan', displayName: 'Faruzan', assetName: 'faruzan'),
  CharacterData(id: 'fischl', displayName: 'Fischl', assetName: 'fischl'),
  CharacterData(id: 'freminet', displayName: 'Freminet', assetName: 'freminet'),
  CharacterData(id: 'gaming', displayName: 'Gaming', assetName: 'gaming'),
  CharacterData(id: 'gorou', displayName: 'Gorou', assetName: 'gorou'),
  CharacterData(
    id: 'heizou',
    displayName: 'Shikanoin Heizou',
    assetName: 'heizou',
  ),
  CharacterData(id: 'kachina', displayName: 'Kachina', assetName: 'kachina'),
  CharacterData(id: 'kaeya', displayName: 'Kaeya', assetName: 'kaeya'),
  CharacterData(id: 'kaveh', displayName: 'Kaveh', assetName: 'kaveh'),
  CharacterData(id: 'kujou', displayName: 'Kujou Sara', assetName: 'kujou'),
  CharacterData(id: 'kuki', displayName: 'Kuki Shinobu', assetName: 'kuki'),
  CharacterData(id: 'layla', displayName: 'Layla', assetName: 'layla'),
  CharacterData(id: 'lisa', displayName: 'Lisa', assetName: 'lisa'),
  CharacterData(id: 'lynette', displayName: 'Lynette', assetName: 'lynette'),
  CharacterData(id: 'mika', displayName: 'Mika', assetName: 'mika'),
  CharacterData(
    id: 'ningguang',
    displayName: 'Ningguang',
    assetName: 'ningguang',
  ),
  CharacterData(id: 'noelle', displayName: 'Noelle', assetName: 'noelle'),
  CharacterData(id: 'ororon', displayName: 'Ororon', assetName: 'ororon'),
  CharacterData(id: 'razor', displayName: 'Razor', assetName: 'razor'),
  CharacterData(id: 'rosaria', displayName: 'Rosaria', assetName: 'rosaria'),
  CharacterData(id: 'sayu', displayName: 'Sayu', assetName: 'sayu'),
  CharacterData(id: 'sethos', displayName: 'Sethos', assetName: 'sethos'),
  CharacterData(id: 'sucrose', displayName: 'Sucrose', assetName: 'sucrose'),
  CharacterData(id: 'thoma', displayName: 'Thoma', assetName: 'thoma'),
  CharacterData(id: 'traveler', displayName: 'Traveler', assetName: 'traveler'),
  CharacterData(
    id: 'xiangling',
    displayName: 'Xiangling',
    assetName: 'xiangling',
  ),
  CharacterData(id: 'xingqiu', displayName: 'Xingqiu', assetName: 'xingqiu'),
  CharacterData(id: 'xinyan', displayName: 'Xinyan', assetName: 'xinyan'),
  CharacterData(id: 'yaoyao', displayName: 'Yaoyao', assetName: 'yaoyao'),
  CharacterData(id: 'yunjin', displayName: 'Yun Jin', assetName: 'yunjin'),
];

/// Legacy list for backward compatibility
@deprecated
const List<String> genshinCharacters = [
  'albedo',
  'alhaitham',
  'aloy',
  'arlecchino',
  'ayaka',
  'ayato',
  'baizhu',
  'chasca',
  'chiori',
  'citlali',
  'clorinde',
  'cyno',
  'dehya',
  'diluc',
  'emilie',
  'escoffier',
  'eula',
  'flins',
  'furina',
  'ganyu',
  'hutao',
  'itto',
  'jean',
  'kazuha',
  'keqing',
  'kinich',
  'klee',
  'kokomi',
  'lyney',
  'mavuika',
  'mona',
  'mualani',
  'nahida',
  'navia',
  'neuvillette',
  'nilou',
  'qiqi',
  'raiden',
  'shenhe',
  'sigewinne',
  'tartaglia',
  'tighnari',
  'venti',
  'wanderer',
  'wriothesley',
  'xiao',
  'xianyun',
  'xilonen',
  'yae',
  'yelan',
  'yoimiya',
  'zhongli',
  'aino',
  'amber',
  'barbara',
  'beidou',
  'bennett',
  'candace',
  'charlotte',
  'chevreuse',
  'chongyun',
  'collei',
  'dahlia',
  'diona',
  'dori',
  'faruzan',
  'fischl',
  'freminet',
  'gaming',
  'gorou',
  'heizou',
  'kachina',
  'kaeya',
  'kaveh',
  'kujou',
  'kuki',
  'layla',
  'lisa',
  'lynette',
  'mika',
  'ningguang',
  'noelle',
  'ororon',
  'razor',
  'rosaria',
  'sayu',
  'sethos',
  'sucrose',
  'thoma',
  'traveler',
  'xiangling',
  'xingqiu',
  'xinyan',
  'yaoyao',
  'yunjin',
];

/// Get display name for a character by ID
String getGenshinCharacterDisplayName(String id) {
  final character = genshinCharactersData.firstWhere(
    (char) => char.id == id.toLowerCase(),
    orElse: () => CharacterData(id: id, displayName: id, assetName: id),
  );
  return character.displayName;
}

/// Get asset path for a character by ID
String getGenshinCharacterAssetName(String id) {
  final character = genshinCharactersData.firstWhere(
    (char) => char.id == id.toLowerCase(),
    orElse: () => CharacterData(id: id, displayName: id, assetName: id),
  );
  return character.assetName;
}
