// Список персонажів Zenless Zone Zero
const List<String> zzzCharacters = [
  'anby',
  'nicole',
  'billy',
  'nekomata',
  'corin',
  'ellen',
  'koleda',
  'ben',
  'anton',
  'soukaku',
  'lycaon',
  'grace',
  'rina',
  'soldier_11',
  'lucy',
  'piper',
  'burnice',
  'caesar',
  'jane',
  'seth',
  'qingyi',
  'zhu_yuan',
  'belle',
  'wise',
  'yanagi',
  'lighter',
  'harumasa',
  'miyabi',
  'evelyn',
  'pulchra',
  'astra',
];

String getCharacterDisplayName(String id) {
  final Map<String, String> displayNames = {
    'anby': 'Anby',
    'nicole': 'Nicole',
    'billy': 'Billy',
    'nekomata': 'Nekomata',
    'corin': 'Corin',
    'ellen': 'Ellen',
    'koleda': 'Koleda',
    'ben': 'Ben',
    'anton': 'Anton',
    'soukaku': 'Soukaku',
    'lycaon': 'Von Lycaon',
    'grace': 'Grace',
    'rina': 'Rina',
    'soldier_11': 'Soldier 11',
    'lucy': 'Lucy',
    'piper': 'Piper',
    'burnice': 'Burnice',
    'caesar': 'Caesar',
    'jane': 'Jane',
    'seth': 'Seth',
    'qingyi': 'Qingyi',
    'zhu_yuan': 'Zhu Yuan',
    'belle': 'Belle',
    'wise': 'Wise',
    'yanagi': 'Yanagi',
    'lighter': 'Lighter',
    'harumasa': 'Harumasa',
    'miyabi': 'Miyabi',
    'evelyn': 'Evelyn',
    'pulchra': 'Pulchra',
    'astra': 'Astra',
  };

  return displayNames[id.toLowerCase()] ?? id;
}
